# Generated by Django 4.1 on 2022-11-09 05:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "General Member"),
                            (1, "Secretary"),
                            (2, "Treasurer"),
                            (3, "President"),
                            (4, "Senior Advisor"),
                        ],
                        default=0,
                        verbose_name="position",
                    ),
                ),
                (
                    "school",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Columbia College"),
                            (1, "School of Engineering and Applied Science"),
                            (2, "Barnard College"),
                            (3, "School of General Studies"),
                            (4, "Other"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="school",
                    ),
                ),
                (
                    "class_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Freshman"),
                            (1, "Sophomore"),
                            (2, "Junior"),
                            (3, "Senior"),
                            (4, "Masters"),
                            (5, "Doctorate"),
                            (6, "Alumni"),
                            (7, "Other"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="class year",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Lion"),
                            (1, "Drum"),
                            (2, "Cymbal"),
                            (3, "Gong"),
                            (4, "Monk"),
                            (5, "Other"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="role type",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shows.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="show date"),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        editable=False,
                        help_text="time of the first round of the show, updated automatically",
                        null=True,
                        verbose_name="show time",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Venue name or room number if on campus",
                        max_length=80,
                        verbose_name="venue address",
                    ),
                ),
                (
                    "is_campus",
                    models.BooleanField(default=False, verbose_name="on campus"),
                ),
                (
                    "lions",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Number of lions"
                    ),
                ),
                ("pending", models.BooleanField(default=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Draft"), (1, "Published"), (2, "Closed")],
                        default=0,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Full"), (1, "Normal"), (2, "Urgent")], default=1
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shows",
                        related_query_name="show",
                        to="shows.contact",
                    ),
                ),
                (
                    "performers",
                    models.ManyToManyField(
                        related_name="performed_shows",
                        related_query_name="performed_show",
                        through="shows.Role",
                        to="shows.member",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pointed_shows",
                        related_query_name="pointed_show",
                        to="shows.member",
                        verbose_name="point person",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        related_query_name="round",
                        to="shows.show",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shows.show"
            ),
        ),
    ]
