# Generated by Django 4.1 on 2022-11-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=60),
        ),
    ]
