# Generated by Django 4.1 on 2022-11-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0003_alter_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="is_out_of_city",
            field=models.BooleanField(default=False, verbose_name="out of city"),
        ),
    ]
