# Generated by Django 4.1 on 2023-01-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0005_add_notes_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="payment_method",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Cash"), (1, "Venmo"), (2, "PayPal"), (3, "Check")],
                default=0,
                verbose_name="payment method",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
    ]
