# Generated by Django 4.1 on 2022-11-09 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackUser",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=60, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_user",
                        to="shows.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlackChannel",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=60, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "briefing_ts",
                    models.CharField(
                        default="",
                        help_text="Slack ts for initial briefing message in the channel",
                        max_length=24,
                        verbose_name="briefing timestamp",
                    ),
                ),
                (
                    "show",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel",
                        to="shows.show",
                    ),
                ),
            ],
        ),
    ]
