# Generated by Django 4.1 on 2022-11-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackchannel",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
